### ISSUE TITLE
items left-margins not equals

### ISSUE THREAD

**Issue by boomsya** [Joseph82/PinnedList-Android#4]
in demo the same problem in VWY letters

![screenshot_1492517593](https://cloud.githubusercontent.com/assets/8008462/25130137/c7d74326-2449-11e7-8489-caeaae3e24cd.png)

**Comment by boomsya** [comment]
sorry :) i have found option "layout_pin_width" in src :) all OK

**Comment by Joseph82** [comment]
Good :) Then I'm gonna close the issue.
