### ISSUE TITLE
OnClick

### ISSUE THREAD

**Issue by boomsya** [Joseph82/PinnedList-Android#5]
hi

can you show a sample code of declare OnClick event on item?

**Comment by boomsya** [comment]
oh. i found solution :)
i have added:
```
public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
.......
holder.itemView.setOnClickListener(new View.OnClickListener()
..
}
```
in ContactAdapter.java

**Comment by Joseph82** [comment]
Yes, exactly. That's something not actually related with the library. You still have the `RecylerView.Adapter` and you can do whatever you want on top
