### ISSUE TITLE
Where i can found support for GridLayoutManager

### ISSUE THREAD

**Issue by santhoshrao519** [Joseph82/PinnedList-Android#8]
Firstly thanks for providing awesome library, but i would like to use it with GridLayoutManager. You have mentioned in docs that there is support for it, but i'm unable to get it done. Please help out @KenVanHoeylandt @Joseph82

**Comment by Joseph82** [comment]
Hi @santhoshrao519  unfortunately the `GridLayoutManager` is not supported. This is why in the documentation you find it in `TODO` section. 
I don't have time to work on that, but you are very welcome to contribute.

**Comment by santhoshrao519** [comment]
Please work on it brother, my job depends on achieving it ..please help
me..i have tried many libraries, but none of them worked
